### ISSUE TITLE
Map function based on map name

### ISSUE THREAD

**Issue by pascalduez** [pascalduez/postcss-map#4]
```js
var opts = {
  basePath: 'css/',
  maps: [ 'breakpoints.yml', 'fonts.yml' ]
};
```
```css
.sowieso {
  font-family: fonts(text);
}
@media (min-width: breakpoints(medium)) {
  .sowieso {
    width: 100%;
  }
}
```

**Comment by thedeeno** [comment]
Hmm, can we reopen this? I frequently define a function to access my maps in sass. It'd be great if this plugin provided the same by default (or supplied an option to turn it on).

Imo, `color: colors(green)` reads much nicer than `color: map(colors, green)`. If I rely on the default map feature linked above I lose organizational control. Plus it's less semantic: `color: map(green)`.

**Comment by pascalduez** [comment]
Hi,

this issue is not closed, and I still like the idea so there are pretty good chances it will land.
I'll try to find a free slot this week.

**Comment by pascalduez** [comment]
Just thinking out loud:

think of some sort of alias configuration.
```js
var opts = {
  basePath: 'css/',
  maps: [ 
    { file: 'breakpoints.yml', alias: 'bp' },
    'fonts.yml' 
  ]
};
```
```css
.sowieso {
  font-family: fonts(text);
}
@media (min-width: bp(medium)) {
  .sowieso {
    width: 100%;
  }
}
```
