### ISSUE TITLE
Add a `standard` option

### ISSUE THREAD

**Issue by pascalduez** [pascalduez/postcss-map#5]
``` yaml
#dummy.yml
foo: 'value'
```

``` css
.sowieso {
  content: map(dummy, foo);
}
```

Would be transpiled to:

``` css
:root {
  --dummy-foo: 'value';
}
.sowieso {
  content: var(--dummy-foo);
}
```
