### ISSUE TITLE
ES6 Module support? 

### ISSUE THREAD

**Issue by kevinSuttle** [pascalduez/postcss-map#76]
Wondering if it's possible for usage to be supported in ES6 modules. Consider the following. 

```js
// Colors.js
const Colors = {
  highlightGreen = {
    name: 'Highlight Green',
    hex: '#3acfb6',
    uses: []
  },

export default Colors;
```

```css
import highlightGreen from `./Colors`;

button {
  background-color: highlightGreen.hex;
}
```
