### ISSUE TITLE
Option to exclude filename from map?

### ISSUE THREAD

**Issue by ben-eb** [pascalduez/postcss-map#9]
So the current syntax is quite verbose if you have a single `config.yml` file:

```css
h1 {
    color: map(config, headings, color);
}
```

It might be nice to allow this syntax in these cases:

```css
h1 {
    color: map(headings, color);
}
```

It would be useful if you have a small-medium size website and only have a handful of variables that you use with postcss-map.
